### ISSUE TITLE
Potential Version Conflict

### ISSUE THREAD

**Issue by DVicendese** [lamm-mit/GraphReasoning#3]
Hi Markus,

I was attempting to run your scripts and it stalled at setup.py.  It was working fine up to 
Collecting torchaudio (from graphreasoning==0.2.0)
Using cached torchaudio-2.3.1-cp312-cp312-win_amd64.whl.metadata (6.4 kB)
INFO: pip is looking at multiple versions of graphreasoning to determine which version is compatible with other requirements. This could take a while.

Then I received this error message
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement huggingface-cli (from graphreasoning) (from versions: none)
ERROR: No matching distribution found for huggingface-cli

I am running Python 3.12.4 at the command line.

Thank you,

Don

**Comment by lamm-mit** [comment]
Thanks for raising this. It should be fixed now.
